services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    environment:
      - TZ=${TZ:-America/New_York}
    ports:
      - '9090:9090'
    networks:
      - proxy
    dns:
      - 192.168.50.1
      - 1.1.1.1
    volumes:
      - /home/andrew/containers/unpoller-unifi/prometheus/config:/etc/prometheus
      - /home/andrew/containers/unpoller-unifi/prometheus/data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.local.zeebali.com`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.local.zeebali.com`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    environment:
      - TZ=${TZ:-America/New_York}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP:-false}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}      
    ports:
      - '3000:3000'
    networks:
      - proxy
    dns:
      - 192.168.50.1
      - 1.1.1.1
    volumes:
      - /home/andrew/containers/unpoller-unifi/grafana/data:/var/lib/grafana
      - /home/andrew/containers/unpoller-unifi/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /home/andrew/containers/unpoller-unifi/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local.zeebali.com`)"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.local.zeebali.com`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
    container_name: unpoller
    environment:
      - TZ=${TZ}
      - UP_INFLUXDB_DISABLE=${UP_INFLUXDB_DISABLE}
      - UP_POLLER_DEBUG=${UP_POLLER_DEBUG}
      - UP_UNIFI_DYNAMIC=${UP_UNIFI_DYNAMIC}
      - UP_PROMETHEUS_HTTP_LISTEN=${UP_PROMETHEUS_HTTP_LISTEN}
      - UP_PROMETHEUS_NAMESPACE=${UP_PROMETHEUS_NAMESPACE}
      - UP_UNIFI_CONTROLLER_0_VERIFY_SSL=${UP_UNIFI_CONTROLLER_0_VERIFY_SSL}
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=${UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES}
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=${UP_UNIFI_CONTROLLER_0_SAVE_EVENTS}
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=${UP_UNIFI_CONTROLLER_0_SAVE_IDS}
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=${UP_UNIFI_CONTROLLER_0_SAVE_SITES}
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=${UP_UNIFI_CONTROLLER_0_SAVE_DPI}
      - UP_UNIFI_CONTROLLER_0_URL=${UP_UNIFI_CONTROLLER_0_URL}
      - UP_UNIFI_CONTROLLER_0_USER=${UP_UNIFI_CONTROLLER_0_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UP_UNIFI_CONTROLLER_0_PASS}
      - UP_UNIFI_CONTROLLER_0_SITE=${UP_UNIFI_CONTROLLER_0_SITE}
    ports:
      - '9130:9130'
    networks:
      - proxy
    dns:
      - 192.168.50.1
      - 1.1.1.1

# optional log viewer for docker containers
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
    ports:
      - '8383:8080'
    networks:
      - proxy
    dns:
      - 192.168.50.1
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=http"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.local.zeebali.com`)"
      - "traefik.http.middlewares.dozzle-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dozzle.middlewares=dozzle-https-redirect"
      - "traefik.http.routers.dozzle-secure.entrypoints=https"
      - "traefik.http.routers.dozzle-secure.rule=Host(`dozzle.local.zeebali.com`)"
      - "traefik.http.routers.dozzle-secure.tls=true"
      - "traefik.http.routers.dozzle-secure.service=dozzle"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true